Repository AstarVienna/ScopeSim, pull requests merged in 2024-01, with the labels that each got.

#324 Include ScopeSim_Data in notebook tests
  .github/workflows/notebooks_dispatch.yml
Labels: tests

#326 Use PyPI badge for Python versions
  README.md
Labels: documentation

#330 Allow runnotebooks.sh to run without arguments
  runnotebooks.sh
Labels: tests

#335 Use new linkchecker action
  .github/workflows/markdown_link_check.yml
Labels: tests

#336 Upgrade numpy to 1.26.3 and some other dependencies
  poetry.lock
  pyproject.toml
Labels: dependencies

#327 Drop support for Python 3.8
  poetry.lock
  pyproject.toml
Labels: dependencies

#339 Improve logging
  poetry.lock
  pyproject.toml
  scopesim/__init__.py
  scopesim/commands/user_commands.py
  scopesim/defaults.yaml
  scopesim/detector/detector.py
  scopesim/detector/detector_array.py
  scopesim/effects/apertures.py
  scopesim/effects/detector_list.py
  scopesim/effects/effects_utils.py
  scopesim/effects/electronic.py
  scopesim/effects/psf_utils.py
  scopesim/effects/shutter.py
  scopesim/effects/spectral_efficiency.py
  scopesim/effects/spectral_trace_list.py
  scopesim/effects/spectral_trace_list_utils.py
  scopesim/effects/ter_curves.py
  scopesim/effects/ter_curves_utils.py
  scopesim/optics/fov.py
  scopesim/optics/fov_manager_utils.py
  scopesim/optics/fov_utils.py
  scopesim/optics/image_plane.py
  scopesim/optics/image_plane_utils.py
  scopesim/optics/optical_element.py
  scopesim/optics/optics_manager.py
  scopesim/optics/radiometry_utils.py
  scopesim/optics/surface.py
  scopesim/optics/surface_utils.py
  scopesim/server/database.py
  scopesim/server/download_utils.py
  scopesim/server/github_utils.py
  scopesim/source/source.py
  scopesim/source/source_utils.py
  scopesim/tests/test_utils_functions.py
  scopesim/utils.py
Labels: dependencies, refactor, API

#341 Rearrange CI tests
  .github/workflows/notebooks_dispatch.yml
  .github/workflows/notebooks_with_irdb_clone.yml
  .github/workflows/tests.yml
  scopesim/tests/tests_server/test_database.py
Labels: tests

#343 Add test to see whether all Python files can be imported.
  scopesim/detector/nghxrg.py
  scopesim/tests/profiling/profile_hawki_results.txt
  scopesim/tests/profiling/profile_hawki_run.py
  scopesim/tests/test_import_all.py
  scopesim/tests/tests_integrations/tst_ScopeSim_MET_LSS.py
  scopesim/tests/tests_server/test_database.py
Labels: tests

#348 Replace "Telescopy" with "ScopeSim" in README
  README.md
Labels: documentation

#349 Further improvements to logging
  poetry.lock
  pyproject.toml
  scopesim/__init__.py
  scopesim/defaults.yaml
  scopesim/tests/conftest.py
  scopesim/tests/test_logging.py
  scopesim/utils.py
Labels: enhancement, refactor

#353 Use logger instead of print
  scopesim/effects/electronic.py
Labels: refactor

#354 Minor logging fixes in download module
  scopesim/server/database.py
  scopesim/server/download_utils.py
Labels: refactor

#313 Add DeprecationWarnings for fov_grid methods
  pyproject.toml
  scopesim/effects/apertures.py
  scopesim/effects/detector_list.py
  scopesim/effects/metis_lms_trace_list.py
  scopesim/effects/psfs.py
  scopesim/effects/shifts.py
  scopesim/effects/spectral_trace_list_utils.py
  scopesim/effects/surface_list.py
  scopesim/effects/ter_curves.py
Labels: refactor

#351 Resolve recursive bang-strings
  scopesim/__init__.py
  scopesim/effects/effects_utils.py
  scopesim/effects/surface_list.py
  scopesim/effects/ter_curves.py
  scopesim/optics/optics_manager.py
  scopesim/tests/test_utils_functions.py
  scopesim/utils.py
  scopesim/version.py
Labels: bug, enhancement
