Repository AstarVienna/ScopeSim, pull requests merged in 2024-07, with the labels that each got.

#432 Avoid in-place operations because of dtype conflicts
  scopesim/effects/electronic.py
Labels: effects

#434 Split PSF and Electronic effects into subpackages
  scopesim/effects/electronic.py
  scopesim/effects/electronic/__init__.py
  scopesim/effects/electronic/dmps.py
  scopesim/effects/electronic/electrons.py
  scopesim/effects/electronic/exposure.py
  scopesim/effects/electronic/noise.py
  scopesim/effects/electronic/pixels.py
  scopesim/effects/psf_utils.py
  scopesim/effects/psfs.py
  scopesim/effects/psfs/__init__.py
  scopesim/effects/psfs/analytical.py
  scopesim/effects/psfs/discrete.py
  scopesim/effects/psfs/psf_base.py
  scopesim/effects/psfs/semianalytical.py
  scopesim/tests/tests_effects/test_BasicReadoutNoise.py
  scopesim/tests/tests_effects/test_FVPSF.py
  scopesim/tests/tests_effects/test_NonCommonPathAberation.py
  scopesim/tests/tests_effects/test_PSF.py
  scopesim/tests/tests_optics/test_fov_manager_utils.py
Labels: refactor, effects

#440 Fix some exposure things
  scopesim/detector/detector.py
  scopesim/optics/optical_train.py
  scopesim/tests/test_basic_instrument/test_basic_instrument.py
Labels: bug

#441 Deepcopy readout, to prevent it being overwritten. Closes #439
  scopesim/optics/optical_train.py
Labels: bug

#443 Allow star to be shifted
  scopesim/source/source_templates.py
  scopesim/tests/tests_source/test_source_Source.py
  scopesim/tests/tests_source/test_source_templates.py
Labels: bug

#445 Bump some dependencies to get rid of some indirect ones
  poetry.lock
Labels: dependencies
