Repository AstarVienna/ScopeSim, pull requests merged in 2024-04, with the labels that each got.

#394 Also show scopsim version in bug_report
  scopesim/utils.py
Labels: enhancement

#396 Implement apply decision for quantization
  scopesim/effects/electronic.py
  scopesim/tests/tests_effects/test_AutoExposure.py
Labels: enhancement, effects

#397 Prepare for v0.8.0
  pyproject.toml
  scopesim/commands/user_commands.py
Labels: no release notes

#402 Final merge of dev_master branch
  pyproject.toml
Labels: no release notes

#406 Fix dev_master -> main in readme
  README.md
Labels: documentation
