Repository AstarVienna/ScopeSim, pull requests merged in 2024-02, with the labels that each got.

#361 Further harmonize `filename` kwarg
  scopesim/effects/data_container.py
  scopesim/effects/electronic.py
  scopesim/effects/metis_lms_trace_list.py
  scopesim/tests/mocks/MICADO_SCAO_WIDE/MICADO_IMG_SCAO_WIDE.yaml
  scopesim/tests/mocks/py_objects/yaml_objects.py
  scopesim/tests/mocks/yamls/MICADO_full.yaml
  scopesim/tests/mocks/yamls/test_cfo.yaml
  scopesim/tests/mocks/yamls/test_fpa.yaml
  scopesim/tests/mocks/yamls/test_inst.yaml
  scopesim/tests/mocks/yamls/test_scope.yaml
Labels: refactor

#362 Minor cleanup in `user_commands.py`
  scopesim/commands/user_commands.py
Labels: refactor

#360 Replace printing with logging
  scopesim/commands/user_commands.py
  scopesim/effects/metis_lms_trace_list.py
  scopesim/effects/spectral_trace_list_utils.py
  scopesim/optics/fov_utils.py
  scopesim/optics/optical_train.py
  scopesim/source/source.py
Labels: refactor

#364 Removing currsys as global parameter
  .gitignore
  scopesim/detector/detector.py
  scopesim/detector/detector_array.py
  scopesim/effects/apertures.py
  scopesim/effects/data_container.py
  scopesim/effects/detector_list.py
  scopesim/effects/effects.py
  scopesim/effects/effects_utils.py
  scopesim/effects/electronic.py
  scopesim/effects/psfs.py
  scopesim/effects/shifts.py
  scopesim/effects/spectral_trace_list.py
  scopesim/effects/spectral_trace_list_utils.py
  scopesim/effects/surface_list.py
  scopesim/effects/ter_curves.py
  scopesim/optics/fov.py
  scopesim/optics/fov_manager.py
  scopesim/optics/optical_element.py
  scopesim/optics/optical_train.py
  scopesim/optics/optics_manager.py
  scopesim/optics/radiometry_utils.py
  scopesim/optics/surface.py
  scopesim/tests/test_basic_instrument/test_basic_instrument.py
  scopesim/tests/test_utils_functions.py
  scopesim/tests/tests_optics/test_OpticalElement.py
  scopesim/utils.py
Labels: refactor

#363 Some small dependency- and version-related changes
  poetry.lock
  pyproject.toml
  scopesim/commands/user_commands.py
  scopesim/effects/effects.py
  scopesim/optics/image_plane_utils.py
  scopesim/optics/optical_train.py
  scopesim/rc.py
  scopesim/server/example_data_utils.py
  scopesim/system_dict.py
  scopesim/tests/conftest.py
  scopesim/tests/tests_commands/test_SystemDict.py
Labels: dependencies, refactor

#368 DRAFT : Additional hotfix for the removed currsys
  pyproject.toml
  scopesim/effects/data_container.py
  scopesim/effects/effects_utils.py
  scopesim/effects/fits_headers.py
  scopesim/effects/spectral_trace_list.py
  scopesim/effects/surface_list.py
  scopesim/optics/__init__.py
  scopesim/optics/optics_manager.py
  scopesim/optics/radiometry.py
  scopesim/optics/radiometry_utils.py
  scopesim/optics/surface.py
  scopesim/tests/test_utils_functions.py
  scopesim/tests/tests_effects/test_fits_headers.py
  scopesim/tests/tests_optics/test_OpticalTrain.py
  scopesim/tests/tests_optics/test_RadiometryTable.py
Labels: bug

#370 Also make pdf and epub
  .readthedocs.yaml
Labels: documentation

#373 Workaround for nested dict not acting like a dict
  scopesim/utils.py
Labels: no release notes

#375 Use ChainMap for UserCommands
  poetry.lock
  pyproject.toml
  scopesim/commands/user_commands.py
  scopesim/effects/fits_headers.py
  scopesim/optics/optical_train.py
  scopesim/tests/tests_commands/test_UserCommands.py
Labels: dependencies, refactor, API

#379 Fix RTD Poetry configuration
  .readthedocs.yaml
Labels: documentation

#377 Do not set user commands as rc.__currsys__
  scopesim/effects/data_container.py
  scopesim/effects/electronic.py
  scopesim/effects/fits_headers.py
  scopesim/effects/psf_utils.py
  scopesim/effects/psfs.py
  scopesim/effects/ter_curves.py
  scopesim/effects/ter_curves_utils.py
  scopesim/optics/fov_manager.py
  scopesim/optics/optical_train.py
  scopesim/tests/tests_effects/test_AutoExposure.py
  scopesim/tests/tests_effects/test_fits_headers.py
  scopesim/tests/tests_optics/test_OpticalTrain.py
  scopesim/utils.py
Labels: refactor
