Repository AstarVienna/ScopeSim, pull requests merged in 2024-11, with the labels that each got.

#482 Make `DataContainer` an attribute of `Effect`
  pyproject.toml
  scopesim/effects/data_container.py
  scopesim/effects/effects.py
  scopesim/effects/effects_utils.py
  scopesim/effects/metis_lms_trace_list.py
  scopesim/effects/spectral_efficiency.py
  scopesim/effects/ter_curves.py
  scopesim/optics/optics_manager.py
  scopesim/tests/tests_effects/test_SpectralTraceList.py
Labels: refactor, API, effects

#485 Source object data scaling fix
  scopesim/optics/fov.py
Labels: bug

#493 Add a new top level to CMDS nested mapping to store current simulation run settings
  pyproject.toml
  scopesim/commands/user_commands.py
  scopesim/effects/electronic/exposure.py
  scopesim/effects/fits_headers.py
  scopesim/optics/optical_train.py
  scopesim/tests/test_basic_instrument/test_basic_instrument.py
Labels: enhancement, tests

#497 Limit supported Python version to 3.10 <= x < 3.13
  poetry.lock
  pyproject.toml
Labels: dependencies

#498 Update CHANGELOG for 0.9.0 release
  CHANGELOG.md
  pyproject.toml
Labels: no release notes

#495 Added source scaling test
  scopesim/tests/test_basic_instrument/test_basic_instrument.py
Labels: tests

#500 Improve z_order
  pyproject.toml
  scopesim/effects/apertures.py
  scopesim/effects/detector_list.py
  scopesim/effects/effects.py
  scopesim/effects/electronic/dmps.py
  scopesim/effects/electronic/electrons.py
  scopesim/effects/electronic/exposure.py
  scopesim/effects/electronic/noise.py
  scopesim/effects/electronic/pixels.py
  scopesim/effects/fits_headers.py
  scopesim/effects/metis_lms_trace_list.py
  scopesim/effects/obs_strategies.py
  scopesim/effects/psfs/analytical.py
  scopesim/effects/psfs/discrete.py
  scopesim/effects/psfs/psf_base.py
  scopesim/effects/psfs/semianalytical.py
  scopesim/effects/rotation.py
  scopesim/effects/shifts.py
  scopesim/effects/shutter.py
  scopesim/effects/spectral_efficiency.py
  scopesim/effects/spectral_trace_list.py
  scopesim/effects/spectral_trace_list_utils.py
  scopesim/effects/surface_list.py
  scopesim/effects/ter_curves.py
  scopesim/effects/ter_curves_utils.py
  scopesim/optics/optical_element.py
  scopesim/optics/optics_manager.py
  scopesim/tests/tests_effects/test_Effects.py
  scopesim/tests/tests_integrations/test_3_custom_effects.py
Labels: refactor, effects

#501 Require Templates 0.6.0 and sync from there
  poetry.lock
  pyproject.toml
Labels: dependencies

#502 Move logging config to separate yaml, configure individual loggers
  pyproject.toml
  scopesim/defaults.yaml
  scopesim/logconfig.yaml
  scopesim/rc.py
  scopesim/tests/test_logging.py
  scopesim/utils.py
Labels: refactor

#503 Fix #490: make rescale_imagehdu more robust against dimension mismatches
  scopesim/optics/image_plane_utils.py
  scopesim/tests/mocks/py_objects/imagehdu_objects.py
  scopesim/tests/tests_optics/test_ImagePlane.py
Labels: bug, tests

#506 Fix FieldVaryingPSF
  scopesim/effects/psfs/discrete.py
  scopesim/optics/fov.py
  scopesim/tests/tests_effects/test_FVPSF.py
Labels: bug, effects

#508 Enable DeprecationWarnings by default
  scopesim/__init__.py
Labels: enhancement

#510 Minor fixes for ScopeSimple
  scopesim/commands/scopesimple.py
  scopesim/server/database.py
Labels: bug, enhancement

#496 Cleanup example notebooks
  .readthedocs.yaml
  docs/source/conf.py
  docs/source/examples/1_scopesim_intro.ipynb
  docs/source/examples/2_multiple_telescopes.ipynb
  docs/source/examples/3_custom_effects.ipynb
  docs/source/getting_started.ipynb
  poetry.lock
  pyproject.toml
  scopesim/__init__.py
  scopesim/commands/user_commands.py
  scopesim/server/download_utils.py
  scopesim/tests/mocks/load_basic_instrument.py
Labels: documentation

#514 Fix two more issues with ScopeSimple
  scopesim/commands/scopesimple.py
  scopesim/commands/user_commands.py
  scopesim/effects/fits_headers.py
  scopesim/tests/tests_commands/test_scopesimple.py
Labels: bug

#515 Prepare for 0.9.1 release
  CHANGELOG.md
  pyproject.toml
Labels: no release notes
