Repository AstarVienna/ScopeSim, pull requests merged in 2024-10, with the labels that each got.

#472 Bump some dependency versions
  poetry.lock
  pyproject.toml
Labels: dependencies

#473 Use sphinx-book-theme for RTD
  docs/source/5_liners/bang_strings.ipynb
  docs/source/5_liners/bang_strings.md
  docs/source/5_liners/effects_include.ipynb
  docs/source/5_liners/effects_include.md
  docs/source/5_liners/simulation_parameters.ipynb
  docs/source/5_liners/simulation_parameters.md
  docs/source/5_liners/source_from_images.ipynb
  docs/source/5_liners/source_from_images.md
  docs/source/5_liners/source_point_source_arrays.ipynb
  docs/source/5_liners/source_point_source_arrays.md
  docs/source/conf.py
  poetry.lock
  pyproject.toml
Labels: dependencies, documentation

#474 Don't fail on symlinks for packages path
  pyproject.toml
  scopesim/server/database.py
Labels: bug

#476 Update example notebook to properly show the same observation
  docs/source/examples/2_multiple_telescopes.ipynb
Labels: documentation

#477 Bump two dependencies, use tqdm.auto
  poetry.lock
  pyproject.toml
  scopesim/effects/spectral_trace_list.py
  scopesim/optics/optical_train.py
  scopesim/server/download_utils.py
Labels: dependencies

#478 Cleanup `DataContainer` in preparation for Effect refactoring
  scopesim/effects/data_container.py
  scopesim/effects/effects.py
  scopesim/tests/tests_optics/test_DataContainer.py
Labels: refactor

#480 Bump scipy from 1.11.4 to 1.14.1 and httpx from 0.23.0 to 0.26.0
  poetry.lock
  pyproject.toml
Labels: dependencies

#481 Remove skycalc_cli from dependencies
  poetry.lock
  pyproject.toml
Labels: dependencies

#484 Fix Poisson NaN bug and clarify
  scopesim/effects/electronic/noise.py
  scopesim/tests/tests_effects/test_shot_noise.py
Labels: bug
