Repository AstarVienna/ScopeSim, pull requests merged in 2024-09, with the labels that each got.

#466 Replace NaNs in images, log warning
  scopesim/defaults.yaml
  scopesim/optics/fov.py
  scopesim/tests/tests_optics/test_FieldOfView.py
Labels: enhancement

#469 Update source_from_images.ipynb
  docs/source/5_liners/source_from_images.ipynb
Labels: documentation

#405 Add `SourceField` and subclasses, rework `Source`
  scopesim/effects/fits_headers.py
  scopesim/effects/spectral_efficiency.py
  scopesim/effects/ter_curves.py
  scopesim/effects/ter_curves_utils.py
  scopesim/optics/fov.py
  scopesim/optics/fov_utils.py
  scopesim/optics/image_plane_utils.py
  scopesim/optics/optical_train.py
  scopesim/rc.py
  scopesim/source/source.py
  scopesim/source/source_fields.py
  scopesim/source/source_utils.py
  scopesim/tests/mocks/py_objects/source_objects.py
  scopesim/tests/tests_optics/test_FieldOfView.py
  scopesim/tests/tests_source/test_source_Source.py
  scopesim/tests/tests_source/test_source_templates.py
Labels: refactor

#467 Some small improvement, mostly focused on numpy
  scopesim/effects/electronic/noise.py
  scopesim/effects/obs_strategies.py
  scopesim/tests/tests_effects/test_ReferencePixelBorder.py
  scopesim/tests/tests_effects/test_fits_headers.py
  scopesim/tests/tests_effects/test_obs_strategies.py
  scopesim/tests/tests_optics/test_FieldOfView.py
  scopesim/tests/tests_optics/test_SpectralSurface.py
  scopesim/tests/tests_server/test_database.py
  scopesim/tests/tests_source/test_source_Source.py
Labels: refactor

#426 ScopeSimple
  scopesim/__init__.py
  scopesim/commands/scopesimple.py
  scopesim/effects/electronic/exposure.py
  scopesim/optics/optical_train.py
  scopesim/optics/optics_manager.py
  scopesim/server/__init__.py
  scopesim/server/database.py
  scopesim/tests/test_basic_instrument/test_basic_instrument.py
  scopesim/tests/tests_commands/test_scopesimple.py
Labels: enhancement, API
