Repository AstarVienna/ScopeSim, pull requests merged in 2025-03, with the labels that each got.

#578 Update dependabot.yml
  .github/dependabot.yml
Labels: github_actions

#494 METIS WCU effects
  scopesim/effects/__init__.py
  scopesim/effects/apertures.py
  scopesim/effects/metis_wcu/__init__.py
  scopesim/effects/metis_wcu/fpmask.py
  scopesim/effects/metis_wcu/metis_wcu.py
  scopesim/effects/psfs/psf_base.py
  scopesim/effects/ter_curves.py
  scopesim/optics/fov.py
  scopesim/optics/image_plane_utils.py
  scopesim/optics/optics_manager.py
  scopesim/tests/mocks/files/fp_mask_pinhole.dat
  scopesim/tests/test_utils_functions.py
  scopesim/tests/tests_effects/test_MetisWCU.py
  scopesim/tests/tests_effects/test_fits_headers.py
  scopesim/utils.py
Labels: enhancement, instrument-specific, effects, Pipeline dev.

#587 Further experimentation with dependabot
  .github/dependabot.yml
Labels: no release notes

#586 Ensure at least one pixel in header
  scopesim/optics/image_plane_utils.py
  scopesim/tests/tests_optics/test_ImagePlaneUtils.py
Labels: bugfix

#599 Prepare for 0.9.2 release
  CHANGELOG.md
  poetry.lock
  pyproject.toml
Labels: no release notes

#600 Bump beautifulsoup to 4.13.3 to get rid of deprecation warning
  poetry.lock
  pyproject.toml
Labels: dependencies

#601 Disable GitHub-based webtests by default
  poetry.lock
  pyproject.toml
  scopesim/tests/tests_server/test_database.py
Labels: dependencies, tests
