Repository AstarVienna/ScopeSim, pull requests merged in 2025-05, with the labels that each got.

#651 Make better use of `SourceField` in `FieldOfView`
  scopesim/optics/fov.py
  scopesim/source/source_fields.py
  scopesim/tests/tests_optics/test_FieldOfView.py
Labels: refactor, optics

#652 Bump numpy, astropy, httpx and synphot
  poetry.lock
  pyproject.toml
Labels: dependencies

#653 Deprecate `FieldOfView.spectra`
  scopesim/optics/fov.py
  scopesim/optics/fov_utils.py
  scopesim/tests/tests_optics/test_FieldOfView.py
  scopesim/tests/tests_optics/test_fov_utls.py
Labels: API, optics

#656 Add `zeros_from_header()` utils function
  scopesim/tests/test_utils_functions.py
  scopesim/utils.py
Labels: enhancement

#657 Deprecate adding a `Table` directly to an `ImagePlane`
  scopesim/optics/image_plane.py
  scopesim/tests/tests_optics/test_ImagePlane.py
  scopesim/tests/tests_source/test_source_Source.py
Labels: API, optics

#664 Bump tornado to get rid of security warning
  poetry.lock
Labels: dependencies

#667 Add `._repr_html_()` magic method to `OpticalTrain` for nice notebook display
  scopesim/optics/optical_train.py
Labels: enhancement

#654 Implement simplified IFU mode with cube readout
  pyproject.toml
  scopesim/detector/detector.py
  scopesim/effects/__init__.py
  scopesim/effects/binning_3d.py
  scopesim/effects/detector_list.py
  scopesim/effects/effects_utils.py
  scopesim/effects/psfs/discrete.py
  scopesim/optics/fov.py
  scopesim/optics/fov_manager.py
  scopesim/optics/image_plane.py
  scopesim/optics/image_plane_utils.py
  scopesim/optics/optical_train.py
  scopesim/tests/mocks/basic_instrument/YAML_detector.yaml
  scopesim/tests/mocks/basic_instrument/YAML_mode_simple_ifu.yaml
  scopesim/tests/mocks/basic_instrument/default.yaml
  scopesim/tests/test_basic_instrument/test_basic_instrument.py
  scopesim/tests/tests_effects/test_DetectorList.py
  scopesim/tests/tests_optics/test_FieldOfView.py
  scopesim/tests/tests_optics/test_fov_manager_utils.py
Labels: enhancement, API, effects, Science Team, spectroscopy

#669 Fix source spectral resolution
  scopesim/optics/optical_train.py
  scopesim/tests/tests_integrations/test_flux_is_conserved_through_full_system.py
Labels: bugfix

#660 Add version requirement support for IRDB packages
  poetry.lock
  pyproject.toml
  scopesim/__init__.py
  scopesim/commands/user_commands.py
Labels: enhancement, dependencies

#671 Allow PSF interpolation to be switched off
  scopesim/effects/psfs/discrete.py
Labels: effects

#670 Implement line spread function for IFU cube mode
  pyproject.toml
  scopesim/effects/__init__.py
  scopesim/effects/metis_ifu_simple/__init__.py
  scopesim/effects/metis_ifu_simple/ifu_simple.py
  scopesim/effects/metis_wcu/__init__.py
  scopesim/tests/tests_effects/test_MetisIfuSimple.py
Labels: enhancement, effects, Science Team, spectroscopy

#673 Fix METIS LSF axes orientation
  pyproject.toml
  scopesim/effects/metis_ifu_simple/ifu_simple.py
Labels: bugfix

#674 Use progress bar for spectral traces
  pyproject.toml
  scopesim/effects/metis_lms_trace_list.py
  scopesim/effects/spectral_trace_list_utils.py
Labels: enhancement
