Repository AstarVienna/ScopeSim, pull requests merged in 2025-04, with the labels that each got.

#620 Remove base class check in `Effect.apply_to()`
  scopesim/effects/effects.py
  scopesim/tests/tests_effects/test_Effects.py
Labels: refactor

#628 Bump python-dateutil from 2.8.2 to 2.9.0.post0
  poetry.lock
Labels: dependencies

#633 Check if all ref keys are found in spectra
  scopesim/source/source_fields.py
  scopesim/tests/tests_source/test_source_Source.py
Labels: enhancement

#638 Fix broken flux scaling for extended sources in spectroscopy
  pyproject.toml
  scopesim/optics/fov.py
  scopesim/tests/test_utils_functions.py
  scopesim/tests/tests_optics/test_FieldOfView.py
  scopesim/utils.py
Labels: bugfix, spectroscopy

#631 Ignore non-package directories for bug_report
  scopesim/utils.py
Labels: enhancement

#642 Switch off spammy INFO logs from httpx
  scopesim/logconfig.yaml
Labels: enhancement

#646 Prepare for 0.9.3 release
  CHANGELOG.md
  pyproject.toml
  scopesim/utils.py
Labels: no release notes

#455 ADConversion effect
  scopesim/effects/detector_list.py
  scopesim/effects/electronic/__init__.py
  scopesim/effects/electronic/dmps.py
  scopesim/effects/electronic/electrons.py
  scopesim/effects/fits_headers.py
  scopesim/tests/mocks/MICADO_SCAO_WIDE/multidetector.yaml
  scopesim/tests/test_basic_instrument/test_basic_instrument.py
  scopesim/tests/tests_effects/test_ADConversion.py
  scopesim/tests/tests_effects/test_DetectorModePropertiesSetter.py
  scopesim/tests/tests_effects/test_Quantization.py
Labels: enhancement, effects, Pipeline dev.

#610 Refactor FOV, add `BackgroundSourceField`
  scopesim/effects/detector_list.py
  scopesim/effects/metis_wcu/fpmask.py
  scopesim/effects/metis_wcu/metis_wcu.py
  scopesim/effects/ter_curves.py
  scopesim/optics/fov.py
  scopesim/optics/fov_utils.py
  scopesim/optics/image_plane_utils.py
  scopesim/source/source.py
  scopesim/source/source_fields.py
  scopesim/tests/tests_integrations/test_flux_is_conserved_through_full_system.py
  scopesim/tests/tests_optics/test_FOVManager.py
  scopesim/tests/tests_optics/test_FieldOfView.py
  scopesim/tests/tests_optics/test_fov_utls.py
  scopesim/utils.py
Labels: refactor, API
