Repository AstarVienna/ScopeSim, pull requests merged in 2025-06, with the labels that each got.

#695 Bump spextra from 0.41.3 to 0.41.4
  poetry.lock
Labels: dependencies

#694 Remove unused private attributes from `OpticsManager`
  scopesim/optics/optics_manager.py
Labels: refactor, optics

#697 More logging and another progress bar
  scopesim/effects/metis_lms_trace_list.py
  scopesim/effects/psfs/discrete.py
  scopesim/effects/psfs/psf_base.py
  scopesim/effects/spectral_trace_list.py
Labels: enhancement

#704 Bump astar-utils from 0.3.2 to 0.3.3
  poetry.lock
  pyproject.toml
Labels: dependencies

#700 Refactor and cleanup in `OpticalElement`
  scopesim/optics/optical_element.py
Labels: refactor

#687 Convert to signed float before chopnodcombine
  scopesim/effects/obs_strategies.py
  scopesim/tests/tests_effects/test_obs_strategies.py
Labels: effects, Science Team, imaging

#707 Change `.wave` to `.waveset`
  scopesim/effects/ter_curves.py
  scopesim/optics/optical_train.py
Labels: bugfix, API

#711 Bump internal dependencies
  poetry.lock
  pyproject.toml
Labels: dependencies

#713 Bump synphot from 1.5.0 to 1.6.0
  poetry.lock
  pyproject.toml
Labels: dependencies
