Repository AstarVienna/ScopeSim, pull requests merged in 2025-09, with the labels that each got.

#794 Bump packaging from 23.2 to 25.0
  poetry.lock
  pyproject.toml
Labels: dependencies

#796 Functionality for MOSAIC minimum viable product
  scopesim/effects/__init__.py
  scopesim/effects/metis_lms_trace_list.py
  scopesim/effects/mosaic_trace_list.py
  scopesim/tests/tests_effects/test_mosaic_trace_list.py
Labels: enhancement, instrument-specific, effects, Science Team, spectroscopy

#798 Use `RegularGridInterpolator` for proper extrapolation of small PSF images
  scopesim/effects/psfs/discrete.py
Labels: bugfix, spectroscopy

#800 Add support for Python 3.13
  poetry.lock
  pyproject.toml
Labels: dependencies

#801 Update workflows
  .github/workflows/bump.yml
  .github/workflows/publish_pypi.yml
Labels: github_actions
